### ISSUE TITLE
python main.py error

### ISSUE THREAD

**Issue by PyAllegro** [0x5eba/Skin-Cancer-Segmentation#4]
![error](https://user-images.githubusercontent.com/38966664/48763560-7ee05900-ece8-11e8-8e51-18215b537c79.png)
Hello, can you take a few minutes to help me see this question, 
thank you very much for any help!

**Comment by 0x5eba** [comment]
Hi,
It's really hard to say whats the problem.

Are you sure that the data are loaded correctly?
```python
# Show some random images to verify that everything is ok
image_ids = np.random.choice(dataset_train.image_ids, 3)
for image_id in image_ids:
    image = dataset_train.load_image(image_id)
    mask, class_ids = dataset_train.load_mask(image_id)
    visualize.display_top_masks(image, mask, class_ids, dataset_train.class_names)
```
Is this code show you the right mask and id based on the image loaded?

Also in my code `use_multiprocessing=True` is set to True not False.
Make sure to use my `Mask` directory.

**Comment by PyAllegro** [comment]
First of all, thank you for your kind reply~
1,Is this code show you the right mask and id based on the image loaded?,yes
![figur](https://user-images.githubusercontent.com/38966664/48813575-6d439380-ed72-11e8-9321-503a38152f10.png)
2,my code use_multiprocessing=True is set to True
3,the data are loaded correctly
![image](https://user-images.githubusercontent.com/38966664/48813677-cb707680-ed72-11e8-9ce4-5fec7ff7600b.png)
4,I did not install opencv-python==3.4.2.17，and  I install  keras==2.1 instead of keras==2.2，
because it reported some errors 
![1](https://user-images.githubusercontent.com/38966664/48813974-0aeb9280-ed74-11e8-83c2-8f0e5ac51dad.png)
![2](https://user-images.githubusercontent.com/38966664/48814074-6a49a280-ed74-11e8-8adb-15f59209ddc9.png)
5，my code use keep_dims instead of keepdism,because use keepdim will report the error 
![4](https://user-images.githubusercontent.com/38966664/48815119-3ff9e400-ed78-11e8-8e10-430a984f0b9d.png)
6，After the above changes，when I run python main.py,the whole process is as shown below
![1](https://user-images.githubusercontent.com/38966664/48814624-6e76bf80-ed76-11e8-9198-5864ca50406f.png)
![2](https://user-images.githubusercontent.com/38966664/48814626-6f0f5600-ed76-11e8-9c40-5ebf853331d1.png)
![5](https://user-images.githubusercontent.com/38966664/48816288-9701b800-ed7c-11e8-9fbf-a9c0598321fa.png)

Last but not least, in order to quickly debug the code, I only use the first 100 data
look forward to your reply！

**Comment by 0x5eba** [comment]
The only thing that for me maybe is wrong is that you are using python3.5 instead of the 3.6. Also try to install opencv3 and opencv2.
I don't really know where is the problem, sorry. For me everything works fine.

**Comment by PyAllegro** [comment]
Thank you very much for your reply again, I will change it according to your suggestions， and  I am really sorry that it took up your valuable time to answer my questions. As a novice, I feel that my questions may not have touched on the key points., So I'm sorry to have caused you some confusion. Finally, thank you very much for your impatient help. I really appreciate it!(most of the time, my questions tend to sink into the sea~~.)

**Comment by Asmar-git** [comment]
when i execute python3 main.py and add the data path it gives the following errors:
hali@mivl-1:~/Skin-Cancer-Segmentation$ python3 main.py
Using TensorFlow backend.
Insert the path of Data [ Link /home/../ISIC-Archive-Downloader/Data/ ] : /home/hali/ISIC-Archive-Downloader/Data/
Traceback (most recent call last):
  File "main.py", line 139, in <module>
    image_ids = np.random.choice(dataset_train.image_ids, 3)
  File "mtrand.pyx", line 1126, in mtrand.RandomState.choice
ValueError: a must be non-empty

**Comment by 0x5eba** [comment]
Are you sure that `/home/hali/ISIC-Archive-Downloader/Data/` is not empty? And must have the structure that I explained in the readme.

Also create a new issue thread, I won't replay here anymore.

**Comment by Asmar-git** [comment]
Yes im sure
