### ISSUE TITLE
main.py not working

### ISSUE THREAD

**Issue by Asmar-git** [0x5eba/Skin-Cancer-Segmentation#6]
Yes im sure the DATA folder is not empty

**Comment by Asmar-git** [comment]
when i execute python3 main.py and add the data path it gives the following errors:
hali@mivl-1:~/Skin-Cancer-Segmentation$ python3 main.py
Using TensorFlow backend.
Insert the path of Data [ Link /home/../ISIC-Archive-Downloader/Data/ ] : /home/hali/ISIC-Archive-Downloader/Data/
Traceback (most recent call last):
File "main.py", line 139, in
image_ids = np.random.choice(dataset_train.image_ids, 3)
File "mtrand.pyx", line 1126, in mtrand.RandomState.choice
ValueError: a must be non-empty

**Comment by 0x5eba** [comment]
You have to give me more details.

1) First make sure that the folder is `Segmentation` and not `Segmentations`.
2) Check with both python3.7 and python3.6 using the `requirement.txt` in the repo
3) Print dataset_train (only the first 5 results)
4) Print dataset_train.image_ids (only the first 5 results)

**Comment by Asmar-git** [comment]
Insert the path of Data [ Link /home/../ISIC-Archive-Downloader/Data/ ] : /home/hali/ISIC-Archive-Downloader/Data/
Traceback (most recent call last):
  File "main.py", line 139, in <module>
    image_ids = np.random.choice(dataset_train.image_ids, 3)
  File "mtrand.pyx", line 773, in numpy.random.mtrand.RandomState.choice
ValueError: 'a' cannot be empty unless no samples are taken
**This Occurs with python3.7**
**the folder name is Segmentation**

**Comment by Asmar-git** [comment]
What i think the issue is that while loading the images you think of them as jpg files, but what i have is jpeg images

**Comment by 0x5eba** [comment]
Change https://github.com/0x5eba/Skin-Cancer-Segmentation/blob/master/main.py#L108 `.jpg` to `.jpeg`.
Also, as I said, follow the instruction that I used in the readme, and should work.

**Comment by Asmar-git** [comment]
i've followed all the instructions, changed jpg to jpeg in line 108, still
not working

**Comment by Asmar-git** [comment]
it says : Using TensorFlow backend.
Traceback (most recent call last):
  File "main.py", line 109, in <module>
    if not img:
ValueError: The truth value of an array with more than one element is
ambiguous. Use a.any() or a.all()
